
- include: python.yml
- include: node.yml
- include: postgres.yml

- name: install myagi ubuntu dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
    - libxml2-dev
    - libxslt1.1
    - libxslt1-dev
    - libcurl4-gnutls-dev
    - libjpeg-dev
    - libffi-dev
    - libxmlsec1
    - libxmlsec1-dev
    - libblas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

- name: setup myagi user
  user: name=myagi shell=/bin/bash groups=myagiapps append=yes uid=5000

- name: ensure source dirs
  file: path={{ item }} owner=myagi group=myagiapps mode=2775 state=directory
  with_items:
    - "/home/myagi/src"
  # This dir causes issues with vagrant
  when: ec2_tag_myagi_stack != 'development'
