---

- name: configure postgres apt-get repo key
  apt_key: url=https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present

- name: add postgres apt-get repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

- name: install node
  apt: name={{ item }} update_cache=yes
  with_items:
    - postgresql-server-dev-9.4
    - postgresql-client-9.4
