---

- name: install python
  apt: name={{ item }} update_cache=yes
  with_items:
    - build-essential
    - python
    - python-dev
    - python-virtualenv
    - python-setuptools
    - python-pip
    - virtualenvwrapper
