baseURL: "localhost:1313/"
title: "Myagi"
languageCode: "en"
defaultContentLanguage: "en"
enableMissingTranslationPlaceholders: true

Languages:
  en:
    title: "Myagi"
    weight: 1
  de:
    weight: 2
  es:
    weight: 3
  fr:
    weight: 4
  nl:
    weight: 5
  it:
    weight: 6
