---

- name: configure elasticsearch apt-get repo key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present

- name: remove old elasticsearch repo
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/1.7/debian stable main' state=absent

- name: add elasticsearch apt-get repo
  become: yes
  become_method: sudo
  lineinfile: dest=/etc/apt/sources.list.d/elasticsearch-2.x.list line="deb https://packages.elastic.co/elasticsearch/2.x/debian stable main" create=yes

- name: install elasticsearch
  apt: name={{ item }} update_cache=yes
  with_items:
    - elasticsearch
    - openjdk-7-jdk

- name: sure elasticsearch is up
  service: name=elasticsearch state=started enabled=yes
