---

- name: setup for a worker or a web server
  hosts: tag_myagi_instance_type_web:tag_myagi_instance_type_worker
  gather_facts: no
  sudo: yes
  vars:
      datadog_api_key: "40f0337ba29b1ba6e47f604a1fec8763"
      datadog_config:
        apm_enabled: true
      datadog_checks:
        http_check:
          init_config:
          instances:
            - name: main_site
              url: https://myagi.com/accounts/login/
              timeout: 10
              skip_event: true
            - name: health_check
              url: https://myagi.com/healthcheck/
              timeout: 10
              skip_event: true
      # Required for Datadog
      ansible_os_family: "Ubuntu"
  roles:
    - common
    - myagi
    - hosting
    - { role: Datadog.datadog, become: yes, when: install_datadog == true }
    - {
        role: newrelic,
        become: yes,
        nrinfragent_license_key: 9b81a1bc337ada980e2e225a87de8d9aca4d6cfe,
        nrinfragent_os_name: debian,
        nrinfragent_os_codename: trusty,
        when: install_newrelic == true
      }
