- name: setup for a dev server
  # Variable host can be set from the command line
  hosts: "{{ variable_host | default('development') }}"
  gather_facts: no
  sudo: yes
  vars:
    ec2_tag_Name: development-web
    ec2_tag_myagi_stack: development
    ec2_tag_myagi_instance_type: web_and_worker
    domains:
        - localhost
    access_domain: localhost
    django_environment_vars:
        PYTHONPATH: '/home/myagi/src/myagi:/home/myagi/python'
        DJANGO_SETTINGS_MODULE: 'myagi.settings'
    # For Postgres
    dbpassword: myagi
    dbuser: myagi
    dbnames:
      - myagidb
      - analytics
    # For Redis
    redis_bind: 127.0.0.1
    ansible_os_family: "Debian"
    ansible_processor_cores: 1
    install_newrelic: false
    newrelic_env: staging
  roles:
    - common
    - vagrant
    - postgresql
    - myagi
    - hosting
    - elasticsearch
    - DavidWittman.redis
