---
- name: Builds dev image by running ansible in a container. Use the bin/local/run-docker.sh script for the correct command.
  hosts: localhost

  tasks:
    - name: check for existence of our base image
      shell: "docker images | grep built-by-ansible | grep ex3"
      ignore_errors: yes
      register: image_check

    - name: determine the base image and temp container names
      set_fact:
        base_image: "{{'built-by-ansible:ex3' if image_check.rc == 0 else 'ansible/ubuntu14.04-ansible:latest'}}"
        temp_container_name: ex3_build_{{lookup('pipe', 'date "+%Y%m%d%H%M%S"')}}

    - name: build site by running ansible in a docker container
      command: "docker run
        -v /Users/Alex/Documents/SoftwareDevelopment/projects/myagi/myagi_official/:/home/myagi/src/
        -v /Users/Alex/Documents/SoftwareDevelopment/projects/myagi/infrastructure/:/infrastructure/
        -w /infrastructure/ansible/
        --privileged=true
        --cap-add SYS_ADMIN
        --name={{temp_container_name}}
        {{base_image}}
        ansible-playbook src/dev.yml -c local --extra-vars \"variable_host=localhost\""

    - name: create a docker image from the container
      command: "docker commit
        -c 'EXPOSE 8000'
        {{temp_container_name}}
        built-by-ansible:ex3"

    - name: delete the container once the image has been successfully built
      command: docker rm -f -v {{temp_container_name}}

    - name: run the site in a docker container
      docker:
        name: site3
        image: "built-by-ansible:ex3"
        state: reloaded
        publish_all_ports: yes
