---

- name: setup for FTP machine
  hosts: tag_myagi_instance_type_ftp
  gather_facts: no
  sudo: yes
  vars:
    - ansible_selinux: false
    - sftp_allow_passwords: false
    - sftp_users:
      - name: myagi-ftp
        # Alex has access to the matching private key.
        # This account should really only be used for testing ATM.
        authorized: [myagi-ftp.pub]
        shell: False
      - name: sun-and-ski-ftp
        authorized: [sun-and-ski-ftp.pub]
        shell: False
      - name: moss-bros-ftp
        authorized: [
          moss-bros-ftp.pub,
          # Used by our systems to retrieve data from this account
          moss-bros-ftp-internal.pub
        ]
        shell: False
    - sftp_directories:
      - imports
  roles:
    - common
    - myagi
    - sftp
