---

- name:           set hostname according to ec2
  hostname:       name="{{ ec2_tag_Name }}"
  tags:
     - set_hostname

- name:           set hostname in /etc/hosts
  template:       src=hosts dest=/etc/hosts owner=root group=root mode=0644
  # When building docker instance, this command will fail
  ignore_errors:  yes
  tags:
     - set_hostname

- name:           setup myagi linux groups
  group:          name={{ item }}
  with_items:     "{{ myagigroups }}"

- name:           setup myagi linux users
  user:           name={{ item.key }} shell=/bin/bash groups=myagiadmins,myagiapps append=yes uid={{ item.value.uid }}
  with_dict:      "{{ myagiusers }}"
  when:           item.value.absent == false

- name:           remove old linux users
  user:           name={{ item.key }} remove=yes state=absent
  with_dict:      "{{ myagiusers }}"
  when:           item.value.absent

- name:           setup ssh keys
  authorized_key: user={{ item.key }} key="{{ item.value.pub_key }}"
  with_dict:      "{{ myagiusers }}"
  when:           item.value.absent == false

# Fixes common apt lists issue.
# See http://ubuntuforums.org/showthread.php?t=2078996.
- name:           clear lists
  shell:          rm /var/lib/apt/lists/* -vrf

- name:           apt clean
  shell:          apt-get clean

- name:           install some basic packages
  apt:            name={{ item }} update_cache=yes
  with_items:
    - build-essential
    - git-core
    - subversion
    - bash-completion
    - curl
    - vim-nox
    - htop
    - fail2ban
    - ack-grep
    - tmux
    - htop
    - iftop
    - iotop
    - dstat
    - libssl-dev
    - libcroco3
    - libunistring0
    - gettext

- name:           setup sudoers - 10-myagi
  copy:           src=10-myagi dest=/etc/sudoers.d/10-myagi validate='visudo -cf %s' owner=root group=root mode=0440

- name:           enable auto upgrades - 20auto-upgrades
  copy:           src=20auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades owner=root group=root mode=0644

- name:           enable unattended upgrades - 50unattended-upgrades
  copy:           src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root mode=0644

- name:           install ntp
  apt:            name=ntp update_cache=yes

- name:           ensure ntp is running
  service:        name=ntp state=started enabled=yes
